# Generated by Django 4.1.13 on 2024-03-28 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clave_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='nombre')),
                ('telefono', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000)], verbose_name='telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('clave_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=100, verbose_name='nombre')),
                ('telefono', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000)], verbose_name='telefono')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salario')),
                ('horario', models.CharField(max_length=100, verbose_name='horario')),
                ('numero_de_seguro', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000)], verbose_name='numero_de_seguro')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('clave_PInventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='gas_ven')),
                ('proveedor', models.CharField(max_length=100, verbose_name='total_sur')),
                ('cantidad_producto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Producto')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra')),
                ('fecha_entrada', models.DateField(auto_now_add=True, verbose_name='Fecha de Entrada')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('vendedor', models.CharField(max_length=100, verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('marca', models.CharField(max_length=100, verbose_name='producto')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('clave_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('marca_producto', models.CharField(max_length=100, verbose_name='Marca Producto')),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Producto')),
                ('cantidad_producto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000)], verbose_name='Cantidad Producto')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de entrada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('telefono', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000)], verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('folio_venta', models.AutoField(primary_key=True, serialize=False)),
                ('clave_empleado', models.CharField(max_length=100, verbose_name='Clave del empleado')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('fecha', models.DateField(verbose_name='Fecha de venta')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
            ],
        ),
    ]
