# Generated by Django 4.1.13 on 2024-03-28 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_abarrotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000)], verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000)], verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000000)], verbose_name='Telefono'),
        ),
    ]
